### ISSUE TITLE
Página de inicio

### ISSUE THREAD

**Issue by JCEntrena** [dgiim/sites#1]
Abro issue para comentar ideas sobre una página de inicio en tux.ugr.es/dgiim, que nos permita redirigir a los distintos sitios. Propongo que tengamos al menos un "Quiénes somos", para decir que no representamos al Doble Grado, y alguna cosa más que sea necesario comentar. Cualquier idea es bienvenida, como siempre.

**Comment by mroman42** [comment]
Creo que la página debería tener enlaces en grande a:
- [x] blog
- [x] overflow
- [x] awesome
- [ ] quiénes somos

Y en pequeño, o con menos relevancia, a:
- [x] twitter
- [x] github
- [x] moot
- [ ] calendario

Además, abajo necesita licencia y agradecimientos a la OSL.

**Comment by fdavidcl** [comment]
> El calendario no sé si deberíamos enlazarlo

Hasta ahora el calendario y el foro estaban enlazados entre sí porque son cosas más propias de la carrera que el resto. La verdad es que no me importaría dejarlos en Github (y/o en Tux pero aparte), y centrar lo que hay en Tux en cosas que no sean exclusivas al grado.

**Comment by mroman42** [comment]
Propongo que dejemos en ambos sitios (tux + github.io) el calendario y el foro, pero los enlacemos en pequeño, o sólo entre ellos.

**Comment by mroman42** [comment]
En cualquier caso, la página de inicio está ya redactada en el repositorio de dgiim/home#1. Podemos cerrar esta issue.
