### ISSUE TITLE
Explicar cómo clonar en local

### ISSUE THREAD

**Issue by mroman42** [dgiim/sites#2]
El `README.md` necesita una sección explicando cómo clonar y servir todos los sitios de @dgiim localmente para que cualquiera que quiera aportar pueda probar y ver la previsualización de lo que hace.

**Comment by mroman42** [comment]
Si no me equivoco, los pasos son:
1. Clonar **sites**.
2. Clonar todos los submódulos en sus correspondientes carpetas.
3. Instalar Ruby.
4. Ejecutar `./build.sh`

Y se acaba sirviendo en el puerto `8000`.

Si no me he saltado nada, lo redacto todo y lo añado al `README.md`.

**Comment by fdavidcl** [comment]
Los pasos 1 y 2 se pueden hacer a la vez con un `git clone --recursive`. Creo que además de Ruby hay que instalar _bundler_ (`gem install bundler`). Por lo demás, perfecto.
